logging:
  level:
    ROOT: INFO
    com.example.tenant: INFO

spring:
  datasource:
    # jdbc properties to connect to database
    jdbcUrl: jdbc:mysql://localhost:3306/ManageUser?createDatabaseIfNotExist=true
    username: root
    password: 123456
    isAutoCommit: false
    connectionTimeout: 10000
    maximumPoolSize: 20
    leakDetectionThreshold: 64800
    poolName: spring-boot-hikari-mysql-cp
    maxLifetime: 72000
    data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false

management:
  endpoint.metrics.enabled: true
  endpoints.web.exposure.include: metrics